#include "Code.h"

// A hard-wired table that classifies 8-bit ASCII characters
// into several groups.
char Code::code[256] =
{
    //
    // 0 - 127
    //
    BAD_CODE, SPACE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, NEWLINE_CODE, SPACE_CODE,
    SPACE_CODE, NEWLINE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, BAD_CODE, SPACE_CODE,
    SPACE_CODE, SPACE_CODE, SPACE_CODE, SPACE_CODE,
    SPACE_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    OTHER_LETTER_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    DIGIT_CODE, DIGIT_CODE, DIGIT_CODE, DIGIT_CODE,
    DIGIT_CODE, DIGIT_CODE, DIGIT_CODE, DIGIT_CODE,
    DIGIT_CODE, DIGIT_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, UPPER_CODE,
    UPPER_CODE, UPPER_CODE, UPPER_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, OTHER_LETTER_CODE,
    BAD_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, LOWER_CODE,
    LOWER_CODE, LOWER_CODE, LOWER_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, SPACE_CODE,

    //
    // 128 - 255
    //
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, OTHER_LETTER_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, OTHER_LETTER_CODE, BAD_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, OTHER_LETTER_CODE, BAD_CODE,
    BAD_CODE, BAD_CODE, BAD_CODE, BAD_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, BAD_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, BAD_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE,
    OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE, OTHER_LETTER_CODE
};
