package xmlparser;

public interface XmlParsersym {
    public final static int
      Char_HT = 4,
      Char_LF = 1,
      Char_CR = 2,
      Char_Space = 3,
      Char_Exclamation = 84,
      Char_DoubleQuote = 83,
      Char_Sharp = 91,
      Char_DollarSign = 95,
      Char_Percent = 87,
      Char_Ampersand = 97,
      Char_SingleQuote = 82,
      Char_LeftParen = 88,
      Char_RightParen = 78,
      Char_Star = 85,
      Char_Plus = 90,
      Char_Comma = 89,
      Char_Minus = 61,
      Char_Dot = 72,
      Char_Slash = 92,
      Char_0 = 62,
      Char_1 = 63,
      Char_2 = 64,
      Char_3 = 65,
      Char_4 = 66,
      Char_5 = 67,
      Char_6 = 68,
      Char_7 = 69,
      Char_8 = 70,
      Char_9 = 71,
      Char_Colon = 74,
      Char_SemiColon = 93,
      Char_LessThan = 81,
      Char_Equal = 94,
      Char_GreaterThan = 58,
      Char_QuestionMark = 73,
      Char_AtSign = 96,
      Char_A = 10,
      Char_B = 28,
      Char_C = 15,
      Char_D = 13,
      Char_E = 6,
      Char_F = 29,
      Char_G = 30,
      Char_H = 43,
      Char_I = 8,
      Char_J = 44,
      Char_K = 37,
      Char_L = 7,
      Char_M = 12,
      Char_N = 9,
      Char_O = 16,
      Char_P = 17,
      Char_Q = 38,
      Char_R = 22,
      Char_S = 14,
      Char_T = 5,
      Char_U = 25,
      Char_V = 31,
      Char_W = 45,
      Char_X = 23,
      Char_Y = 19,
      Char_Z = 46,
      Char_LeftBracket = 86,
      Char_BackSlash = 98,
      Char_RightBracket = 79,
      Char_Caret = 99,
      Char__ = 57,
      Char_BackQuote = 100,
      Char_a = 32,
      Char_b = 47,
      Char_c = 39,
      Char_d = 33,
      Char_e = 20,
      Char_f = 48,
      Char_g = 40,
      Char_h = 49,
      Char_i = 34,
      Char_j = 50,
      Char_k = 51,
      Char_l = 11,
      Char_m = 18,
      Char_n = 21,
      Char_o = 26,
      Char_p = 52,
      Char_q = 53,
      Char_r = 41,
      Char_s = 27,
      Char_t = 42,
      Char_u = 54,
      Char_v = 35,
      Char_w = 55,
      Char_x = 24,
      Char_y = 36,
      Char_z = 56,
      Char_LeftBrace = 101,
      Char_VerticalBar = 80,
      Char_RightBrace = 102,
      Char_Tilde = 103,
      Char_NonAsciiBaseChar = 59,
      Char_Ideographic = 60,
      Char_CombiningChar = 75,
      Char_Extender = 76,
      Char_NonAsciiDigit = 77,
      Char_OtherValidChar = 104,
      Char_Unused = 108,
      Char_ExtSubsetMarker = 105,
      Char_ExtParserEntMarker = 106,
      Char_EOF = 107;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "LF",
                 "CR",
                 "Space",
                 "HT",
                 "T",
                 "E",
                 "L",
                 "I",
                 "N",
                 "A",
                 "l",
                 "M",
                 "D",
                 "S",
                 "C",
                 "O",
                 "P",
                 "m",
                 "Y",
                 "e",
                 "n",
                 "R",
                 "X",
                 "x",
                 "U",
                 "o",
                 "s",
                 "B",
                 "F",
                 "G",
                 "V",
                 "a",
                 "d",
                 "i",
                 "v",
                 "y",
                 "K",
                 "Q",
                 "c",
                 "g",
                 "r",
                 "t",
                 "H",
                 "J",
                 "W",
                 "Z",
                 "b",
                 "f",
                 "h",
                 "j",
                 "k",
                 "p",
                 "q",
                 "u",
                 "w",
                 "z",
                 "_",
                 "GreaterThan",
                 "NonAsciiBaseChar",
                 "Ideographic",
                 "Minus",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9",
                 "Dot",
                 "QuestionMark",
                 "Colon",
                 "CombiningChar",
                 "Extender",
                 "NonAsciiDigit",
                 "RightParen",
                 "RightBracket",
                 "VerticalBar",
                 "LessThan",
                 "SingleQuote",
                 "DoubleQuote",
                 "Exclamation",
                 "Star",
                 "LeftBracket",
                 "Percent",
                 "LeftParen",
                 "Comma",
                 "Plus",
                 "Sharp",
                 "Slash",
                 "SemiColon",
                 "Equal",
                 "DollarSign",
                 "AtSign",
                 "Ampersand",
                 "BackSlash",
                 "Caret",
                 "BackQuote",
                 "LeftBrace",
                 "RightBrace",
                 "Tilde",
                 "OtherValidChar",
                 "ExtSubsetMarker",
                 "ExtParserEntMarker",
                 "EOF",
                 "Unused"
             };

    public final static boolean isValidForParser = true;
}
