package javascriptparser;

public interface JavascriptLexersym {
    public final static int
      Char_U0009 = 35,
      Char_U000A = 65,
      Char_U000B = 36,
      Char_U000C = 37,
      Char_U000D = 66,
      Char_Exclamation = 48,
      Char_DoubleQuote = 49,
      Char_DollarSign = 20,
      Char_Percent = 50,
      Char_Ampersand = 38,
      Char_SingleQuote = 51,
      Char_LeftParen = 52,
      Char_RightParen = 53,
      Char_Star = 54,
      Char_Plus = 32,
      Char_Comma = 55,
      Char_Minus = 33,
      Char_Dot = 16,
      Char_Slash = 56,
      Char_zero = 1,
      Char_one__nine = 2,
      Char_Colon = 39,
      Char_SemiColon = 57,
      Char_LessThan = 40,
      Char_Equal = 3,
      Char_GreaterThan = 34,
      Char_QuestionMark = 58,
      Char_A__D = 8,
      Char_E = 4,
      Char_F = 5,
      Char_L = 12,
      Char_U = 15,
      Char_X = 18,
      Char_LeftBracket = 59,
      Char_BackSlash = 21,
      Char_RightBracket = 60,
      Char_Caret = 41,
      Char_Underscore = 19,
      Char_a = 9,
      Char_b = 10,
      Char_c__d = 11,
      Char_e = 6,
      Char_f = 7,
      Char_l = 13,
      Char_n = 22,
      Char_r = 23,
      Char_t = 24,
      Char_u = 14,
      Char_v = 25,
      Char_x = 17,
      Char_LeftBrace = 61,
      Char_VerticalBar = 42,
      Char_RightBrace = 62,
      Char_Tilde = 63,
      Char_U2028__U2029 = 67,
      Char_Generic_Lu = 26,
      Char_Generic_Ll = 27,
      Char_Generic_Lt = 28,
      Char_Generic_Lm = 29,
      Char_Generic_Lo = 30,
      Char_Generic_Mn = 43,
      Char_Generic_Mc = 44,
      Char_Generic_Nd = 45,
      Char_Generic_Nl = 31,
      Char_Generic_Pc = 46,
      Char_Generic_Zs = 47,
      Char_Generic_Cn = 64,
      Char_Illegal = 69,
      Char_EOF = 68;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "zero",
                 "one__nine",
                 "Equal",
                 "E",
                 "F",
                 "e",
                 "f",
                 "A__D",
                 "a",
                 "b",
                 "c__d",
                 "L",
                 "l",
                 "u",
                 "U",
                 "Dot",
                 "x",
                 "X",
                 "Underscore",
                 "DollarSign",
                 "BackSlash",
                 "n",
                 "r",
                 "t",
                 "v",
                 "Generic_Lu",
                 "Generic_Ll",
                 "Generic_Lt",
                 "Generic_Lm",
                 "Generic_Lo",
                 "Generic_Nl",
                 "Plus",
                 "Minus",
                 "GreaterThan",
                 "U0009",
                 "U000B",
                 "U000C",
                 "Ampersand",
                 "Colon",
                 "LessThan",
                 "Caret",
                 "VerticalBar",
                 "Generic_Mn",
                 "Generic_Mc",
                 "Generic_Nd",
                 "Generic_Pc",
                 "Generic_Zs",
                 "Exclamation",
                 "DoubleQuote",
                 "Percent",
                 "SingleQuote",
                 "LeftParen",
                 "RightParen",
                 "Star",
                 "Comma",
                 "Slash",
                 "SemiColon",
                 "QuestionMark",
                 "LeftBracket",
                 "RightBracket",
                 "LeftBrace",
                 "RightBrace",
                 "Tilde",
                 "Generic_Cn",
                 "U000A",
                 "U000D",
                 "U2028__U2029",
                 "EOF",
                 "Illegal"
             };

    public final static boolean isValidForParser = true;
}
