#!/usr/bin/perl -s

# ########################################################################### #
# Description       : Remove system includes from makedepend dependency list  #
# ########################################################################### #

# *************************************************************************** #
# FILE DOCUMENTATION:                                                         #
#                                                                             #
# Strips a makefile of system-specific include files in makedepend-generated  #
# dependency info.                                                            #
#                                                                             #
# Usage: mindepend [-safe] makefile                                           #
#                                                                             #
# If the -safe flag is given, no changes will be made before the              #
# "DO NOT DELETE" line that makedepend depends upon.                          #
#                                                                             #
# *************************************************************************** #

while (<>) {            # For each line in the makefile
    if ($safe) {
        if (! $gotThere) {
            if (/^\# DO NOT DELETE/) {
                $gotThere = 1;
            } else {            # Print w/o change lines before depend section
                print $_;
                next;           # Skip to next makefile line
            }
        }   # got to makedepend section -- fall through to process this line
    }

    if (! /^.*\.o: /) {         # It's not a dependency line
        print $_;
    } elsif (! /\/usr\//) {     # It has no refs to system includes
        print $_;
    } else {
        chop;                   # Kill trailing newline
        @words  = split(/ /);   # Separate out target and deps
        $target = @words[0];
        @deps   = grep(!/^\/usr\//, @words[1..$#words]); # Kill sys deps
        if ($#deps >= 0) {      # Print out line only if some non-sys deps
            print("$target ", join(' ', @deps), "\n");
        }
    }
}
