package javaparser;

public interface JavaKWLexerexp {
    public final static int
      TK_abstract = 1,
      TK_boolean = 2,
      TK_break = 3,
      TK_byte = 4,
      TK_case = 5,
      TK_catch = 6,
      TK_char = 7,
      TK_class = 8,
      TK_const = 9,
      TK_continue = 10,
      TK_default = 11,
      TK_do = 12,
      TK_double = 13,
      TK_else = 14,
      TK_extends = 15,
      TK_false = 16,
      TK_final = 17,
      TK_finally = 18,
      TK_float = 19,
      TK_for = 20,
      TK_goto = 21,
      TK_if = 22,
      TK_implements = 23,
      TK_import = 24,
      TK_instanceof = 25,
      TK_int = 26,
      TK_interface = 27,
      TK_long = 28,
      TK_native = 29,
      TK_new = 30,
      TK_null = 31,
      TK_package = 32,
      TK_private = 33,
      TK_protected = 34,
      TK_public = 35,
      TK_return = 36,
      TK_short = 37,
      TK_static = 38,
      TK_strictfp = 39,
      TK_super = 40,
      TK_switch = 41,
      TK_synchronized = 42,
      TK_this = 43,
      TK_throw = 44,
      TK_throws = 45,
      TK_transient = 46,
      TK_true = 47,
      TK_try = 48,
      TK_void = 49,
      TK_volatile = 50,
      TK_while = 51;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "abstract",
                 "boolean",
                 "break",
                 "byte",
                 "case",
                 "catch",
                 "char",
                 "class",
                 "const",
                 "continue",
                 "default",
                 "do",
                 "double",
                 "else",
                 "extends",
                 "false",
                 "final",
                 "finally",
                 "float",
                 "for",
                 "goto",
                 "if",
                 "implements",
                 "import",
                 "instanceof",
                 "int",
                 "interface",
                 "long",
                 "native",
                 "new",
                 "null",
                 "package",
                 "private",
                 "protected",
                 "public",
                 "return",
                 "short",
                 "static",
                 "strictfp",
                 "super",
                 "switch",
                 "synchronized",
                 "this",
                 "throw",
                 "throws",
                 "transient",
                 "true",
                 "try",
                 "void",
                 "volatile",
                 "while"
             };


    public final static boolean isValidForParser = false;
}
